### ISSUE TITLE
 Problems packaging PySide2 app for iOS

### ISSUE THREAD

**Issue by GenevieveBuckley** [GenevieveBuckley/hellopyside#1]
Similar to https://github.com/GenevieveBuckley/hellopyqt/issues/1

I can't get the app to open in the IOS simulator using "briefcase run". It gets clicked/launched and then crashes immediately.

Version numbers:
* XCode Version 11.5 (11E608c)
* Python 3.7
* PySide2 version 5.13.0
* briefcase version 0.3.0

Note: it's ambiguous to me whether PySide2 officially supports IOS. So it's probably better to try and tackle https://github.com/GenevieveBuckley/hellopyqt/issues/1 first.

**Comment by GenevieveBuckley** [comment]
XCode console output

```
2020-05-24 14:59:54.983583+1000 hellopyside[27973:333753] PythonHome is: /Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Python
2020-05-24 14:59:54.986820+1000 hellopyside[27973:333753] PYTHONPATH is: PYTHONPATH=/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Application Support/com.example.hellopyside/app:/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Application Support/com.example.hellopyside/app_packages
2020-05-24 14:59:54.987054+1000 hellopyside[27973:333753] Initializing Python runtime...
2020-05-24 14:59:55.250501+1000 hellopyside[27973:333753] Installing Python NSLog handler...
2020-05-24 14:59:55.618356+1000 hellopyside[27973:333753] Running 'hellopyside'...
2020-05-24 14:59:55.848585+1000 hellopyside[27973:333753] Application quit abnormally!
2020-05-24 14:59:55.849152+1000 hellopyside[27973:333753] Traceback (most recent call last):
2020-05-24 14:59:55.849511+1000 hellopyside[27973:333753]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Python/lib/python37.zip/runpy.py", line 193, in _run_module_as_main
2020-05-24 14:59:55.850376+1000 hellopyside[27973:333753]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Python/lib/python37.zip/runpy.py", line 85, in _run_code
2020-05-24 14:59:55.851133+1000 hellopyside[27973:333753]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Application Support/com.example.hellopyside/app/hellopyside/__main__.py", line 1, in <module>
2020-05-24 14:59:55.852565+1000 hellopyside[27973:333753]     from hellopyside.app import main
2020-05-24 14:59:55.854608+1000 hellopyside[27973:333753]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Application Support/com.example.hellopyside/app/hellopyside/app.py", line 5, in <module>
2020-05-24 14:59:55.855371+1000 hellopyside[27973:333753]     from PySide2 import QtWidgets
2020-05-24 14:59:55.855713+1000 hellopyside[27973:333753]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Application Support/com.example.hellopyside/app_packages/PySide2/__init__.py", line 51, in <module>
2020-05-24 14:59:55.856551+1000 hellopyside[27973:333753]     _setupQtDirectories()
2020-05-24 14:59:55.856925+1000 hellopyside[27973:333753]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Application Support/com.example.hellopyside/app_packages/PySide2/__init__.py", line 21, in _setupQtDirectories
2020-05-24 14:59:55.858092+1000 hellopyside[27973:333753]     import shiboken2
2020-05-24 14:59:55.858639+1000 hellopyside[27973:333753]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/E0155C27-2CEE-4CAD-9F16-4CA7992BFAE5/hellopyside.app/Library/Application Support/com.example.hellopyside/app_packages/shiboken2/__init__.py", line 27, in <module>
2020-05-24 14:59:55.859399+1000 hellopyside[27973:333753]     from .shiboken2 import *
2020-05-24 14:59:55.859740+1000 hellopyside[27973:333753] ModuleNotFoundError: No module named 'shiboken2.shiboken2'
2020-05-24 14:59:55.928733+1000 hellopyside[27973:333753] *** Assertion failure in void _UIApplicationMainPreparations(int, char **, NSString *__strong, NSString *__strong)(), /Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3920.31.100/UIApplication.m:4765
2020-05-24 14:59:55.929078+1000 hellopyside[27973:333753] Python runtime error: Unable to instantiate the UIApplication delegate instance. No class named PythonAppDelegate is loaded.
2020-05-24 14:59:55.937120+1000 hellopyside[27973:333753] Leaving...
```

**Comment by GenevieveBuckley** [comment]
Russell also left this helpful comment on the [beeware/general Gitter](https://gitter.im/beeware/general):

> One piece of the puzzle that might be helpful in your PySide bughunt; the Briefcase template for iOS assumes (a) that myapp is an executable module, and (b) executing that module will cause the creation of an ObjectiveC object called PythonAppDelegate
(The AppDelegate is iOS’s controller for the app lifecycle)
> That is almost certainly not what PySide/PyQt is creating - no idea what a Qt “iOS app” looks like.
> (from a running code perspective, that is)
